// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/tag_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/repository/tag_repository.go -destination=mocks/repository/mock_tag_repository.go -package=repository
//

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"

	entity "github.com/MizukiShigi/cms-go/internal/domain/entity"
	mock "go.uber.org/mock/gomock"
)

// MockTagRepository is a mock of TagRepository interface.
type MockTagRepository struct {
	ctrl     *mock.Controller
	recorder *MockTagRepositoryMockRecorder
}

// MockTagRepositoryMockRecorder is the mock recorder for MockTagRepository.
type MockTagRepositoryMockRecorder struct {
	mock *MockTagRepository
}

// NewMockTagRepository creates a new mock instance.
func NewMockTagRepository(ctrl *mock.Controller) *MockTagRepository {
	mock := &MockTagRepository{ctrl: ctrl}
	mock.recorder = &MockTagRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTagRepository) EXPECT() *MockTagRepositoryMockRecorder {
	return m.recorder
}

// FindOrCreateByName mocks base method.
func (m *MockTagRepository) FindOrCreateByName(ctx context.Context, tag *entity.Tag) (*entity.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOrCreateByName", ctx, tag)
	ret0, _ := ret[0].(*entity.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOrCreateByName indicates an expected call of FindOrCreateByName.
func (mr *MockTagRepositoryMockRecorder) FindOrCreateByName(ctx, tag any) *mock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOrCreateByName", reflect.TypeOf((*MockTagRepository)(nil).FindOrCreateByName), ctx, tag)
}
