version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./src/Dockerfile
      target: dev
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./src:/app
      # ADCファイルをマウント
      - ~/.config/gcloud:/root/.config/gcloud:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/root/.config/gcloud/application_default_credentials.json

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cms
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d

volumes:
  postgres-data: