version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_URL=postgres://postgres:password@db:5432/cms?sslmode=disable
      - JWT_SECRET=your-secret-key
    depends_on:
      - db
    volumes:
      - .:/app
    command: air -c .air.toml

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cms
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: