// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

// TestToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestToOne(t *testing.T) {
	t.Run("ImageToPostUsingPost", testImageToOnePostUsingPost)
	t.Run("ImageToUserUsingUser", testImageToOneUserUsingUser)
	t.Run("PostToUserUsingUser", testPostToOneUserUsingUser)
}

// TestOneToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOne(t *testing.T) {}

// TestToMany tests cannot be run in parallel
// or deadlocks can occur.
func TestToMany(t *testing.T) {
	t.Run("PostToImages", testPostToManyImages)
	t.Run("PostToTags", testPostToManyTags)
	t.Run("TagToPosts", testTagToManyPosts)
	t.Run("UserToImages", testUserToManyImages)
	t.Run("UserToPosts", testUserToManyPosts)
}

// TestToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneSet(t *testing.T) {
	t.Run("ImageToPostUsingImages", testImageToOneSetOpPostUsingPost)
	t.Run("ImageToUserUsingImages", testImageToOneSetOpUserUsingUser)
	t.Run("PostToUserUsingPosts", testPostToOneSetOpUserUsingUser)
}

// TestToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneRemove(t *testing.T) {}

// TestOneToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneSet(t *testing.T) {}

// TestOneToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneRemove(t *testing.T) {}

// TestToManyAdd tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyAdd(t *testing.T) {
	t.Run("PostToImages", testPostToManyAddOpImages)
	t.Run("PostToTags", testPostToManyAddOpTags)
	t.Run("TagToPosts", testTagToManyAddOpPosts)
	t.Run("UserToImages", testUserToManyAddOpImages)
	t.Run("UserToPosts", testUserToManyAddOpPosts)
}

// TestToManySet tests cannot be run in parallel
// or deadlocks can occur.
func TestToManySet(t *testing.T) {
	t.Run("PostToTags", testPostToManySetOpTags)
	t.Run("TagToPosts", testTagToManySetOpPosts)
}

// TestToManyRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyRemove(t *testing.T) {
	t.Run("PostToTags", testPostToManyRemoveOpTags)
	t.Run("TagToPosts", testTagToManyRemoveOpPosts)
}
